//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:52 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:54 PM(foreman)-)
//


package com.ibmcloud.ws;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibmcloud.ws package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ListToDo_QNAME = new QName("http://ws.ibmcloud.com/", "listToDo");
    private final static QName _DelToDoResponse_QNAME = new QName("http://ws.ibmcloud.com/", "delToDoResponse");
    private final static QName _AuthUser_QNAME = new QName("http://ws.ibmcloud.com/", "authUser");
    private final static QName _AddUser_QNAME = new QName("http://ws.ibmcloud.com/", "addUser");
    private final static QName _ListToDoResponse_QNAME = new QName("http://ws.ibmcloud.com/", "listToDoResponse");
    private final static QName _AddToDo_QNAME = new QName("http://ws.ibmcloud.com/", "addToDo");
    private final static QName _DelToDo_QNAME = new QName("http://ws.ibmcloud.com/", "delToDo");
    private final static QName _AddToDoResponse_QNAME = new QName("http://ws.ibmcloud.com/", "addToDoResponse");
    private final static QName _AddUserResponse_QNAME = new QName("http://ws.ibmcloud.com/", "addUserResponse");
    private final static QName _AuthUserResponse_QNAME = new QName("http://ws.ibmcloud.com/", "authUserResponse");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibmcloud.ws
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DelToDoResponse }
     * 
     */
    public DelToDoResponse createDelToDoResponse() {
        return new DelToDoResponse();
    }

    /**
     * Create an instance of {@link AddToDoResponse }
     * 
     */
    public AddToDoResponse createAddToDoResponse() {
        return new AddToDoResponse();
    }

    /**
     * Create an instance of {@link AddToDo }
     * 
     */
    public AddToDo createAddToDo() {
        return new AddToDo();
    }

    /**
     * Create an instance of {@link DelToDo }
     * 
     */
    public DelToDo createDelToDo() {
        return new DelToDo();
    }

    /**
     * Create an instance of {@link AuthUser }
     * 
     */
    public AuthUser createAuthUser() {
        return new AuthUser();
    }

    /**
     * Create an instance of {@link AddUserResponse }
     * 
     */
    public AddUserResponse createAddUserResponse() {
        return new AddUserResponse();
    }

    /**
     * Create an instance of {@link ListToDo }
     * 
     */
    public ListToDo createListToDo() {
        return new ListToDo();
    }

    /**
     * Create an instance of {@link ListToDoResponse }
     * 
     */
    public ListToDoResponse createListToDoResponse() {
        return new ListToDoResponse();
    }

    /**
     * Create an instance of {@link AddUser }
     * 
     */
    public AddUser createAddUser() {
        return new AddUser();
    }

    /**
     * Create an instance of {@link AuthUserResponse }
     * 
     */
    public AuthUserResponse createAuthUserResponse() {
        return new AuthUserResponse();
    }

    /**
     * Create an instance of {@link Operation }
     * 
     */
    public Operation createOperation() {
        return new Operation();
    }

    /**
     * Create an instance of {@link ToDo }
     * 
     */
    public ToDo createToDo() {
        return new ToDo();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListToDo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "listToDo")
    public JAXBElement<ListToDo> createListToDo(ListToDo value) {
        return new JAXBElement<ListToDo>(_ListToDo_QNAME, ListToDo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelToDoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "delToDoResponse")
    public JAXBElement<DelToDoResponse> createDelToDoResponse(DelToDoResponse value) {
        return new JAXBElement<DelToDoResponse>(_DelToDoResponse_QNAME, DelToDoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "authUser")
    public JAXBElement<AuthUser> createAuthUser(AuthUser value) {
        return new JAXBElement<AuthUser>(_AuthUser_QNAME, AuthUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddUser }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "addUser")
    public JAXBElement<AddUser> createAddUser(AddUser value) {
        return new JAXBElement<AddUser>(_AddUser_QNAME, AddUser.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ListToDoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "listToDoResponse")
    public JAXBElement<ListToDoResponse> createListToDoResponse(ListToDoResponse value) {
        return new JAXBElement<ListToDoResponse>(_ListToDoResponse_QNAME, ListToDoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddToDo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "addToDo")
    public JAXBElement<AddToDo> createAddToDo(AddToDo value) {
        return new JAXBElement<AddToDo>(_AddToDo_QNAME, AddToDo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DelToDo }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "delToDo")
    public JAXBElement<DelToDo> createDelToDo(DelToDo value) {
        return new JAXBElement<DelToDo>(_DelToDo_QNAME, DelToDo.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddToDoResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "addToDoResponse")
    public JAXBElement<AddToDoResponse> createAddToDoResponse(AddToDoResponse value) {
        return new JAXBElement<AddToDoResponse>(_AddToDoResponse_QNAME, AddToDoResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AddUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "addUserResponse")
    public JAXBElement<AddUserResponse> createAddUserResponse(AddUserResponse value) {
        return new JAXBElement<AddUserResponse>(_AddUserResponse_QNAME, AddUserResponse.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link AuthUserResponse }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://ws.ibmcloud.com/", name = "authUserResponse")
    public JAXBElement<AuthUserResponse> createAuthUserResponse(AuthUserResponse value) {
        return new JAXBElement<AuthUserResponse>(_AuthUserResponse_QNAME, AuthUserResponse.class, null, value);
    }

}
