//
// Generated By:JAX-WS RI IBM 2.2.1-07/09/2014 01:52 PM(foreman)- (JAXB RI IBM 2.2.3-07/07/2014 12:54 PM(foreman)-)
//


package com.ibmcloud.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

@WebService(name = "ToDoWebServices", targetNamespace = "http://ws.ibmcloud.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface ToDoWebServices {


    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.ibmcloud.ws.Operation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addUser", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.AddUser")
    @ResponseWrapper(localName = "addUserResponse", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.AddUserResponse")
    @Action(input = "http://ws.ibmcloud.com/ToDoWebServices/addUserRequest", output = "http://ws.ibmcloud.com/ToDoWebServices/addUserResponse")
    public Operation addUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns com.ibmcloud.ws.Operation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "authUser", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.AuthUser")
    @ResponseWrapper(localName = "authUserResponse", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.AuthUserResponse")
    @Action(input = "http://ws.ibmcloud.com/ToDoWebServices/authUserRequest", output = "http://ws.ibmcloud.com/ToDoWebServices/authUserResponse")
    public Operation authUser(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.ibmcloud.ws.Operation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "addToDo", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.AddToDo")
    @ResponseWrapper(localName = "addToDoResponse", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.AddToDoResponse")
    @Action(input = "http://ws.ibmcloud.com/ToDoWebServices/addToDoRequest", output = "http://ws.ibmcloud.com/ToDoWebServices/addToDoResponse")
    public Operation addToDo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns com.ibmcloud.ws.Operation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "delToDo", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.DelToDo")
    @ResponseWrapper(localName = "delToDoResponse", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.DelToDoResponse")
    @Action(input = "http://ws.ibmcloud.com/ToDoWebServices/delToDoRequest", output = "http://ws.ibmcloud.com/ToDoWebServices/delToDoResponse")
    public Operation delToDo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        String arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        String arg3);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.ibmcloud.ws.Operation
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "listToDo", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.ListToDo")
    @ResponseWrapper(localName = "listToDoResponse", targetNamespace = "http://ws.ibmcloud.com/", className = "com.ibmcloud.ws.ListToDoResponse")
    @Action(input = "http://ws.ibmcloud.com/ToDoWebServices/listToDoRequest", output = "http://ws.ibmcloud.com/ToDoWebServices/listToDoResponse")
    public Operation listToDo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
